# Dockerfile
FROM continuumio/miniconda3
RUN conda update --yes -c conda-forge  --all  &&  conda install --yes -c conda-forge numpy gdal flask flask-cors flask-compress grequests owslib pillow && conda update --yes -c conda-forge  --all  && conda clean --all --yes




